apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

namespace: abuse-api-dev
images:
- name: docker-dcu-local.artifactory.secureserver.net/phishstory-service
  newTag: dev

configMapGenerator:
- literals:
  - sysenv=dev
  - DATABASE_IMPACTED='False'
  - ELASTIC_APM_ENVIRONMENT=dev
  name: env-specific-values
