---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "phishstory-service"
  namespace: "abuse-api-prod"
  labels:
    app: "phishstory-service"
spec:
  replicas: 2
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: "phishstory-service"
    spec:
      imagePullSecrets:
        -
          name: "k8s-artifactory-creds"
      containers:
        -
          name: "phishstory-service"
          imagePullPolicy: "Always"
          image: "artifactory.secureserver.net:10014/docker-dcu-local/phishstory-service:REPLACE_WITH_GIT_COMMIT"
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: sysenv
            value: prod
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: KEYFILE
            value: /keyfiles/key.txt
          - name: SNOW_PASS
            valueFrom:
              secretKeyRef:
                name: svc-snow
                key: password
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-api
                key: password
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-cmap-service
                key: password
          volumeMounts:
          - name: encryption-keys
            mountPath: /keyfiles
            readOnly: true

      volumes:
        - name: encryption-keys
          secret:
            secretName: encryption-key-files