---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "phishstory-service"
  namespace: "abuse-api-prod"
  labels:
    app: "phishstory-service"
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "phishstory-service"
  template:
    metadata:
      labels:
        app: "phishstory-service"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "phishstory-service"
          imagePullPolicy: "Always"
          image: "docker-dcu-local.artifactory.secureserver.net/phishstory-service:REPLACE_WITH_GIT_COMMIT"
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: sysenv
            value: prod
          - name: DATABASE_IMPACTED
            value: 'False'
          - name: BUILD_DATE
            value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          - name: SNOW_PASS
            valueFrom:
              secretKeyRef:
                name: svc-snow
                key: password
          - name: BROKER_PASS
            valueFrom:
              secretKeyRef:
                name: amqp-phishstory-service
                key: password
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-phishstory-service
                key: password
