---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "phishstory-service"
  labels:
    app: "phishstory-service"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "phishstory-service"
  template:
    metadata:
      labels:
        app: "phishstory-service"
    spec:
      imagePullSecrets:
        -
          name: "dcu-artifactory-creds"
      containers:
        -
          name: "phishstory-service"
          image: "docker-dcu-local.artifactory.secureserver.net/phishstory-service"
          envFrom:
            - configMapRef:
                name: env-specific-values
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
          - name: SNOW_PASS
            valueFrom:
              secretKeyRef:
                name: svc-snow-v2
                key: password
          - name: MULTIPLE_BROKERS
            valueFrom:
              secretKeyRef:
                name: amqp-shared-creds
                key: multiple_brokers_grandma
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: mongodb-connection-string-v2 
                key: url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm-access
                key: secret

